### ISSUE TITLE
LiFePo4

### ISSUE THREAD

**Issue by Highcooley** [makevoid/esk8-calc#1]
A verry cool tool!
Could you please add LiFePo4 cells with 3.2 Volts? Thank you!

**Comment by jamescarlson** [comment]
came here to open this exact issue haha, please do add it!

**Comment by makevoid** [comment]
thanks both for the feedback, this w/e I had a bit of time and did it, check it out:

http://calc.esk8.it/#{"batt-type-lipo":2,"batt-cells":10,"motor-kv":190,"system-efficiency":85,"motor-pulley-teeth":15,"wheel-pulley-teeth":36,"wheel-size":90}|

**Comment by Highcooley** [comment]
Great, thanks! However, why LiFePo4 work perfectly on my mobile but are not available as a choice and don't compute on my desktop PC with chrome browser, nobody knows :-) "batt-type-lipo":2" gets interpreted as Li-Ion.

**Comment by makevoid** [comment]
You probably have a local cache, refresh with the shift key pressed and you should see the latest version

**Comment by Highcooley** [comment]
Thanks, it's working. I thought I had the Shift key pressed when I refreshed...my bad, sorry!
